[project]
name = "cespy"
version = "0.1.0"
description = ""
authors = [
    {name = "Ryota Kobayashi",email = "s.woods.m.29@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]

[tool.poetry]
packages = [{include = "cespy", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
