from typing import Any

def figure(*args: Any, **kwargs: Any) -> Any: ...

def subplot(*args: Any, **kwargs: Any) -> Any: ...

def subplots(*args: Any, **kwargs: Any) -> tuple[Any, Any]: ...

def plot(*args: Any, **kwargs: Any) -> list[Any]: ...

def semilogx(*args: Any, **kwargs: Any) -> list[Any]: ...

def loglog(*args: Any, **kwargs: Any) -> list[Any]: ...

def hist(*args: Any, **kwargs: Any) -> tuple[Any, Any, Any]: ...

def legend(*args: Any, **kwargs: Any) -> Any: ...


def xlabel(label: str, *args: Any, **kwargs: Any) -> None: ...

def ylabel(label: str, *args: Any, **kwargs: Any) -> None: ...

def title(label: str, *args: Any, **kwargs: Any) -> None: ...

def tight_layout(*args: Any, **kwargs: Any) -> None: ...

def savefig(
    fname: str,
    *,
    dpi: float | int | None = ...,
    bbox_inches: str | None = ...,
    transparent: bool | None = ...,
    **kwargs: Any,
) -> None: ...

def close(*args: Any, **kwargs: Any) -> None: ...

def show() -> None: ...

def grid(b: bool | None = ..., *, which: str | None = ..., axis: str | None = ...) -> None: ...
